// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: adminDNSpb.proto

package admind

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandAdminDNS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TipoComm      string `protobuf:"bytes,1,opt,name=tipoComm,proto3" json:"tipoComm,omitempty"`           //create-update-delete
	NombreDominio string `protobuf:"bytes,2,opt,name=nombreDominio,proto3" json:"nombreDominio,omitempty"` //nombre.dominio
	TipoCambio    string `protobuf:"bytes,3,opt,name=tipoCambio,proto3" json:"tipoCambio,omitempty"`       //nil - <nombre>|<ip>
	ParamNuevo    string `protobuf:"bytes,4,opt,name=paramNuevo,proto3" json:"paramNuevo,omitempty"`       //ip - <valornuevo> - nil
}

func (x *CommandAdminDNS) Reset() {
	*x = CommandAdminDNS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminDNSpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandAdminDNS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAdminDNS) ProtoMessage() {}

func (x *CommandAdminDNS) ProtoReflect() protoreflect.Message {
	mi := &file_adminDNSpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAdminDNS.ProtoReflect.Descriptor instead.
func (*CommandAdminDNS) Descriptor() ([]byte, []int) {
	return file_adminDNSpb_proto_rawDescGZIP(), []int{0}
}

func (x *CommandAdminDNS) GetTipoComm() string {
	if x != nil {
		return x.TipoComm
	}
	return ""
}

func (x *CommandAdminDNS) GetNombreDominio() string {
	if x != nil {
		return x.NombreDominio
	}
	return ""
}

func (x *CommandAdminDNS) GetTipoCambio() string {
	if x != nil {
		return x.TipoCambio
	}
	return ""
}

func (x *CommandAdminDNS) GetParamNuevo() string {
	if x != nil {
		return x.ParamNuevo
	}
	return ""
}

type DnsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack string `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *DnsResponse) Reset() {
	*x = DnsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminDNSpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsResponse) ProtoMessage() {}

func (x *DnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adminDNSpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsResponse.ProtoReflect.Descriptor instead.
func (*DnsResponse) Descriptor() ([]byte, []int) {
	return file_adminDNSpb_proto_rawDescGZIP(), []int{1}
}

func (x *DnsResponse) GetAck() string {
	if x != nil {
		return x.Ack
	}
	return ""
}

var File_adminDNSpb_proto protoreflect.FileDescriptor

var file_adminDNSpb_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x44, 0x4e, 0x53, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x64, 0x22, 0x93, 0x01, 0x0a, 0x0f, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x44, 0x4e, 0x53, 0x12, 0x1a,
	0x0a, 0x08, 0x74, 0x69, 0x70, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x69, 0x70, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x12, 0x24, 0x0a, 0x0d, 0x6e, 0x6f,
	0x6d, 0x62, 0x72, 0x65, 0x44, 0x6f, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x44, 0x6f, 0x6d, 0x69, 0x6e, 0x69, 0x6f,
	0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x69, 0x70, 0x6f, 0x43, 0x61, 0x6d, 0x62, 0x69, 0x6f, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x69, 0x70, 0x6f, 0x43, 0x61, 0x6d, 0x62, 0x69, 0x6f,
	0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x4e, 0x75, 0x65, 0x76, 0x6f, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x4e, 0x75, 0x65, 0x76, 0x6f,
	0x22, 0x1f, 0x0a, 0x0b, 0x44, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x63,
	0x6b, 0x32, 0x51, 0x0a, 0x0f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x44, 0x4e, 0x53, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x0c, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x44, 0x4e, 0x53,
	0x43, 0x6f, 0x6d, 0x6d, 0x12, 0x17, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x64, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x44, 0x4e, 0x53, 0x1a, 0x13, 0x2e,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x64, 0x2e, 0x44, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x02, 0x5a, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_adminDNSpb_proto_rawDescOnce sync.Once
	file_adminDNSpb_proto_rawDescData = file_adminDNSpb_proto_rawDesc
)

func file_adminDNSpb_proto_rawDescGZIP() []byte {
	file_adminDNSpb_proto_rawDescOnce.Do(func() {
		file_adminDNSpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_adminDNSpb_proto_rawDescData)
	})
	return file_adminDNSpb_proto_rawDescData
}

var file_adminDNSpb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_adminDNSpb_proto_goTypes = []interface{}{
	(*CommandAdminDNS)(nil), // 0: admind.CommandAdminDNS
	(*DnsResponse)(nil),     // 1: admind.DnsResponse
}
var file_adminDNSpb_proto_depIdxs = []int32{
	0, // 0: admind.AdminDNSService.AdminDNSComm:input_type -> admind.CommandAdminDNS
	1, // 1: admind.AdminDNSService.AdminDNSComm:output_type -> admind.DnsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_adminDNSpb_proto_init() }
func file_adminDNSpb_proto_init() {
	if File_adminDNSpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_adminDNSpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandAdminDNS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adminDNSpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DnsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_adminDNSpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adminDNSpb_proto_goTypes,
		DependencyIndexes: file_adminDNSpb_proto_depIdxs,
		MessageInfos:      file_adminDNSpb_proto_msgTypes,
	}.Build()
	File_adminDNSpb_proto = out.File
	file_adminDNSpb_proto_rawDesc = nil
	file_adminDNSpb_proto_goTypes = nil
	file_adminDNSpb_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AdminDNSServiceClient is the client API for AdminDNSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminDNSServiceClient interface {
	// admin envia comando -> dns recibe
	AdminDNSComm(ctx context.Context, in *CommandAdminDNS, opts ...grpc.CallOption) (*DnsResponse, error)
}

type adminDNSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminDNSServiceClient(cc grpc.ClientConnInterface) AdminDNSServiceClient {
	return &adminDNSServiceClient{cc}
}

func (c *adminDNSServiceClient) AdminDNSComm(ctx context.Context, in *CommandAdminDNS, opts ...grpc.CallOption) (*DnsResponse, error) {
	out := new(DnsResponse)
	err := c.cc.Invoke(ctx, "/admind.AdminDNSService/AdminDNSComm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminDNSServiceServer is the server API for AdminDNSService service.
type AdminDNSServiceServer interface {
	// admin envia comando -> dns recibe
	AdminDNSComm(context.Context, *CommandAdminDNS) (*DnsResponse, error)
}

// UnimplementedAdminDNSServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAdminDNSServiceServer struct {
}

func (*UnimplementedAdminDNSServiceServer) AdminDNSComm(context.Context, *CommandAdminDNS) (*DnsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminDNSComm not implemented")
}

func RegisterAdminDNSServiceServer(s *grpc.Server, srv AdminDNSServiceServer) {
	s.RegisterService(&_AdminDNSService_serviceDesc, srv)
}

func _AdminDNSService_AdminDNSComm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandAdminDNS)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminDNSServiceServer).AdminDNSComm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admind.AdminDNSService/AdminDNSComm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminDNSServiceServer).AdminDNSComm(ctx, req.(*CommandAdminDNS))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdminDNSService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "admind.AdminDNSService",
	HandlerType: (*AdminDNSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminDNSComm",
			Handler:    _AdminDNSService_AdminDNSComm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "adminDNSpb.proto",
}
