// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: brokerDNSpb.proto

package brodns

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClienteBrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommCliente string `protobuf:"bytes,1,opt,name=commCliente,proto3" json:"commCliente,omitempty"`
}

func (x *ClienteBrRequest) Reset() {
	*x = ClienteBrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brokerDNSpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClienteBrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClienteBrRequest) ProtoMessage() {}

func (x *ClienteBrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brokerDNSpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClienteBrRequest.ProtoReflect.Descriptor instead.
func (*ClienteBrRequest) Descriptor() ([]byte, []int) {
	return file_brokerDNSpb_proto_rawDescGZIP(), []int{0}
}

func (x *ClienteBrRequest) GetCommCliente() string {
	if x != nil {
		return x.CommCliente
	}
	return ""
}

type DnsClientResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpDominio string `protobuf:"bytes,1,opt,name=ipDominio,proto3" json:"ipDominio,omitempty"`
	Reloj     string `protobuf:"bytes,2,opt,name=reloj,proto3" json:"reloj,omitempty"`
	IpDNS     string `protobuf:"bytes,3,opt,name=ipDNS,proto3" json:"ipDNS,omitempty"`
}

func (x *DnsClientResponse) Reset() {
	*x = DnsClientResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brokerDNSpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DnsClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsClientResponse) ProtoMessage() {}

func (x *DnsClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brokerDNSpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsClientResponse.ProtoReflect.Descriptor instead.
func (*DnsClientResponse) Descriptor() ([]byte, []int) {
	return file_brokerDNSpb_proto_rawDescGZIP(), []int{1}
}

func (x *DnsClientResponse) GetIpDominio() string {
	if x != nil {
		return x.IpDominio
	}
	return ""
}

func (x *DnsClientResponse) GetReloj() string {
	if x != nil {
		return x.Reloj
	}
	return ""
}

func (x *DnsClientResponse) GetIpDNS() string {
	if x != nil {
		return x.IpDNS
	}
	return ""
}

var File_brokerDNSpb_proto protoreflect.FileDescriptor

var file_brokerDNSpb_proto_rawDesc = []byte{
	0x0a, 0x11, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x44, 0x4e, 0x53, 0x70, 0x62, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x72, 0x6f, 0x64, 0x6e, 0x73, 0x22, 0x34, 0x0a, 0x10, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x42, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x65, 0x22, 0x5d, 0x0a, 0x11, 0x44, 0x6e, 0x73, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x70, 0x44, 0x6f, 0x6d, 0x69,
	0x6e, 0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x70, 0x44, 0x6f, 0x6d,
	0x69, 0x6e, 0x69, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x6c, 0x6f, 0x6a, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x6c, 0x6f, 0x6a, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x70,
	0x44, 0x4e, 0x53, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x70, 0x44, 0x4e, 0x53,
	0x32, 0x5a, 0x0a, 0x10, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x44, 0x4e, 0x53, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0d, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x44, 0x4e,
	0x53, 0x43, 0x6f, 0x6d, 0x6d, 0x12, 0x18, 0x2e, 0x62, 0x72, 0x6f, 0x64, 0x6e, 0x73, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x42, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x62, 0x72, 0x6f, 0x64, 0x6e, 0x73, 0x2e, 0x44, 0x6e, 0x73, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x02, 0x5a, 0x00,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_brokerDNSpb_proto_rawDescOnce sync.Once
	file_brokerDNSpb_proto_rawDescData = file_brokerDNSpb_proto_rawDesc
)

func file_brokerDNSpb_proto_rawDescGZIP() []byte {
	file_brokerDNSpb_proto_rawDescOnce.Do(func() {
		file_brokerDNSpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_brokerDNSpb_proto_rawDescData)
	})
	return file_brokerDNSpb_proto_rawDescData
}

var file_brokerDNSpb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_brokerDNSpb_proto_goTypes = []interface{}{
	(*ClienteBrRequest)(nil),  // 0: brodns.ClienteBrRequest
	(*DnsClientResponse)(nil), // 1: brodns.DnsClientResponse
}
var file_brokerDNSpb_proto_depIdxs = []int32{
	0, // 0: brodns.BrokerDNSService.BrokerDNSComm:input_type -> brodns.ClienteBrRequest
	1, // 1: brodns.BrokerDNSService.BrokerDNSComm:output_type -> brodns.DnsClientResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_brokerDNSpb_proto_init() }
func file_brokerDNSpb_proto_init() {
	if File_brokerDNSpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_brokerDNSpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClienteBrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brokerDNSpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DnsClientResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_brokerDNSpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_brokerDNSpb_proto_goTypes,
		DependencyIndexes: file_brokerDNSpb_proto_depIdxs,
		MessageInfos:      file_brokerDNSpb_proto_msgTypes,
	}.Build()
	File_brokerDNSpb_proto = out.File
	file_brokerDNSpb_proto_rawDesc = nil
	file_brokerDNSpb_proto_goTypes = nil
	file_brokerDNSpb_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BrokerDNSServiceClient is the client API for BrokerDNSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BrokerDNSServiceClient interface {
	// broker envia comando del cliente -> DNS responde apropiadamente
	BrokerDNSComm(ctx context.Context, in *ClienteBrRequest, opts ...grpc.CallOption) (*DnsClientResponse, error)
}

type brokerDNSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerDNSServiceClient(cc grpc.ClientConnInterface) BrokerDNSServiceClient {
	return &brokerDNSServiceClient{cc}
}

func (c *brokerDNSServiceClient) BrokerDNSComm(ctx context.Context, in *ClienteBrRequest, opts ...grpc.CallOption) (*DnsClientResponse, error) {
	out := new(DnsClientResponse)
	err := c.cc.Invoke(ctx, "/brodns.BrokerDNSService/BrokerDNSComm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerDNSServiceServer is the server API for BrokerDNSService service.
type BrokerDNSServiceServer interface {
	// broker envia comando del cliente -> DNS responde apropiadamente
	BrokerDNSComm(context.Context, *ClienteBrRequest) (*DnsClientResponse, error)
}

// UnimplementedBrokerDNSServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBrokerDNSServiceServer struct {
}

func (*UnimplementedBrokerDNSServiceServer) BrokerDNSComm(context.Context, *ClienteBrRequest) (*DnsClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BrokerDNSComm not implemented")
}

func RegisterBrokerDNSServiceServer(s *grpc.Server, srv BrokerDNSServiceServer) {
	s.RegisterService(&_BrokerDNSService_serviceDesc, srv)
}

func _BrokerDNSService_BrokerDNSComm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClienteBrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerDNSServiceServer).BrokerDNSComm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/brodns.BrokerDNSService/BrokerDNSComm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerDNSServiceServer).BrokerDNSComm(ctx, req.(*ClienteBrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BrokerDNSService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "brodns.BrokerDNSService",
	HandlerType: (*BrokerDNSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BrokerDNSComm",
			Handler:    _BrokerDNSService_BrokerDNSComm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "brokerDNSpb.proto",
}
